# Generated by Django 3.2.9 on 2021-11-13 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='N/D', max_length=40)),
                ('city', models.CharField(default='N/D', max_length=40)),
                ('suburb', models.CharField(default='N/D', max_length=40)),
                ('street', models.CharField(default='N/D', max_length=40)),
                ('residence', models.CharField(default='N/D', max_length=40)),
                ('reference', models.CharField(default='N/D', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/D', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/D', max_length=40)),
                ('description', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/D', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileName', models.CharField(default='N/D', max_length=40)),
                ('description', models.CharField(default='N/D', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/D', max_length=40)),
                ('description', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/D', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='N/D', max_length=40)),
                ('password', models.CharField(default='N/D', max_length=40)),
                ('firstName', models.CharField(default='N/D', max_length=40)),
                ('lastName', models.CharField(default='N/D', max_length=50)),
                ('dni', models.CharField(default='N/D', max_length=30)),
                ('age', models.CharField(default='N/D', max_length=3)),
                ('principalCellphone', models.CharField(default='N/D', max_length=10)),
                ('auxiliarCellphone', models.CharField(default='N/D', max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.address')),
                ('profileType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.profiletype')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.role')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/D', max_length=70)),
                ('birthDate', models.DateField()),
                ('color', models.CharField(default='N/D', max_length=50)),
                ('size', models.CharField(default='N/D', max_length=10)),
                ('gender', models.CharField(default='N/D', max_length=10)),
                ('isSterilized', models.BooleanField(default=False)),
                ('isAdopted', models.BooleanField(default=False)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.breed')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.petcategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.user')),
                ('vaccines', models.ManyToManyField(to='backend_app.Vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('update', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.module')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.role')),
            ],
        ),
    ]
