# Generated by Django 3.2.7 on 2021-10-14 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('suburb', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=40)),
                ('residence', models.CharField(max_length=40)),
                ('reference', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/D', max_length=40)),
                ('description', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/D', max_length=40)),
                ('description', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('update', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.module')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.role')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileName', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=3)),
                ('principalCellphone', models.CharField(max_length=10)),
                ('auxiliarCellphone', models.CharField(max_length=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.address')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
