# Generated by Django 3.2.9 on 2021-11-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.CharField(default='N/D', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='motto',
            field=models.CharField(default='N/D', max_length=300),
        ),
    ]
