# Generated by Django 3.2.7 on 2021-10-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileName', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=3)),
                ('principalCellphone', models.CharField(max_length=10)),
                ('auxiliarCellphone', models.CharField(max_length=10)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.address')),
                ('profileType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.profiletype')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.role')),
            ],
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
