# Generated by Django 3.2.7 on 2021-10-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_auto_20211021_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('birthDate', models.DateField()),
                ('breed', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('isSterilized', models.BooleanField(default=False)),
                ('isAdopted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.petcategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.user')),
                ('vaccines', models.ManyToManyField(to='backend_app.Vaccine')),
            ],
        ),
    ]
