# Generated by Django 3.2.9 on 2021-11-17 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_auto_20211117_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('accepted', models.BooleanField(default=False)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.user')),
            ],
        ),
    ]
