# Generated by Django 3.2.9 on 2021-11-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_adoptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secureAnswer',
            field=models.CharField(default='N/D', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='secureQuestion',
            field=models.CharField(default='N/D', max_length=300),
        ),
    ]
