# Generated by Django 3.2.9 on 2021-11-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_auto_20211117_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiletype',
            old_name='profileName',
            new_name='name',
        ),
    ]
