# Generated by Django 3.2.9 on 2021-11-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_rename_profilename_profiletype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='N/D', max_length=2024),
        ),
    ]
