# Generated by Django 3.2.9 on 2021-11-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='showDetails',
            field=models.BooleanField(default=False),
        ),
    ]
